### ISSUE TITLE
How to use TypedArray to convert php array to js Uint8Array

### ISSUE THREAD

**Issue by forcemeter** [ArrayIterator/TypedArray#1]
How to use TypedArray to convert php array to js Uint8Array

**Comment by ArrayIterator** [comment]
> How to use TypedArray to convert php array to js Uint8Array

I am so sorry about very late reply.

Truly, I does not have much time to resolve this repository.

`Uint8Array`  according [MDN Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array)

```
The Uint8Array typed array represents an array of 8-bit unsigned integers.
The contents are initialized to 0. Once established, 
you can reference elements in the array using the object's methods, 
or using standard array index syntax (that is, using bracket notation).
```

Cause I have no free time 😞  , please consider to fork the repository.

to create `uint8array` use this php lib just doing

```php
<?php
use ArrayIterator\TypedArray\Uint8Array;
$array = [];// array content

$uInt8Array = new Uint8Array($array);
```

When use javascript, you must convert php array to javascript object (maybe json)

```javascript
let jsonArray = {"key": "content", "key_2": "content"};
let length = 0;
// cause php commonly server as object that does not have length key, we must loop it
for (let key in jsonArray) {
    length++;
}
let uint8ar = new Uint8Array(length);

```
